"""Description of changes

Revision ID: 79e8288f62d9
Revises: 
Create Date: 2024-11-26 00:06:49.587525

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79e8288f62d9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('faculty', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.String(length=255), nullable=False))
        batch_op.alter_column('bio',
               existing_type=sa.TEXT(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('faculty', schema=None) as batch_op:
        batch_op.alter_column('bio',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.drop_column('image_url')

    # ### end Alembic commands ###
