"""Add image_url to Faculty

Revision ID: 979541e6e6e5
Revises: 79e8288f62d9
Create Date: 2024-12-16 00:32:54.970544

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '979541e6e6e5'
down_revision = '79e8288f62d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('faculty', schema=None) as batch_op:
        batch_op.add_column(sa.Column('photo', sa.String(length=200), nullable=True))
        batch_op.drop_column('image_url')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('faculty', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.VARCHAR(length=255), nullable=False))
        batch_op.drop_column('photo')

    # ### end Alembic commands ###
