"""Add PDF fields to Faculty

Revision ID: c1fa3aa49492
Revises: d076881516ba
Create Date: 2025-11-17 00:33:18.637818

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c1fa3aa49492'
down_revision = 'd076881516ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('faculty', schema=None) as batch_op:
        batch_op.add_column(sa.Column('achievement_pdf', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('research_pdf', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('faculty', schema=None) as batch_op:
        batch_op.drop_column('created_at')
        batch_op.drop_column('research_pdf')
        batch_op.drop_column('achievement_pdf')

    # ### end Alembic commands ###
